// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: grpc-proto/invoice.proto

package invoice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MODELS
type Invoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Amount        float32                `protobuf:"fixed32,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invoice) Reset() {
	*x = Invoice{}
	mi := &file_grpc_proto_invoice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoice) ProtoMessage() {}

func (x *Invoice) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_invoice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoice.ProtoReflect.Descriptor instead.
func (*Invoice) Descriptor() ([]byte, []int) {
	return file_grpc_proto_invoice_proto_rawDescGZIP(), []int{0}
}

func (x *Invoice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Invoice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Invoice) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Invoice) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Invoice) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// REQUEST MSGS
type GetAllInvoicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllInvoicesRequest) Reset() {
	*x = GetAllInvoicesRequest{}
	mi := &file_grpc_proto_invoice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllInvoicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllInvoicesRequest) ProtoMessage() {}

func (x *GetAllInvoicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_invoice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllInvoicesRequest.ProtoReflect.Descriptor instead.
func (*GetAllInvoicesRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_invoice_proto_rawDescGZIP(), []int{1}
}

type GetInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoiceRequest) Reset() {
	*x = GetInvoiceRequest{}
	mi := &file_grpc_proto_invoice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceRequest) ProtoMessage() {}

func (x *GetInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_invoice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceRequest.ProtoReflect.Descriptor instead.
func (*GetInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_invoice_proto_rawDescGZIP(), []int{2}
}

func (x *GetInvoiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Amount        float32                `protobuf:"fixed32,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvoiceRequest) Reset() {
	*x = CreateInvoiceRequest{}
	mi := &file_grpc_proto_invoice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceRequest) ProtoMessage() {}

func (x *CreateInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_invoice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoiceRequest.ProtoReflect.Descriptor instead.
func (*CreateInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_invoice_proto_rawDescGZIP(), []int{3}
}

func (x *CreateInvoiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateInvoiceRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateInvoiceRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CreateInvoiceRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type UpdateInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Status        *string                `protobuf:"bytes,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Method        *string                `protobuf:"bytes,4,opt,name=method,proto3,oneof" json:"method,omitempty"`
	Amount        *float32               `protobuf:"fixed32,5,opt,name=amount,proto3,oneof" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInvoiceRequest) Reset() {
	*x = UpdateInvoiceRequest{}
	mi := &file_grpc_proto_invoice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInvoiceRequest) ProtoMessage() {}

func (x *UpdateInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_invoice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInvoiceRequest.ProtoReflect.Descriptor instead.
func (*UpdateInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_invoice_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateInvoiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateInvoiceRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateInvoiceRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *UpdateInvoiceRequest) GetMethod() string {
	if x != nil && x.Method != nil {
		return *x.Method
	}
	return ""
}

func (x *UpdateInvoiceRequest) GetAmount() float32 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

type DeleteInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInvoiceRequest) Reset() {
	*x = DeleteInvoiceRequest{}
	mi := &file_grpc_proto_invoice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInvoiceRequest) ProtoMessage() {}

func (x *DeleteInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_invoice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInvoiceRequest.ProtoReflect.Descriptor instead.
func (*DeleteInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_invoice_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteInvoiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// RESPONSE MSGS
type GetAllInvoicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoices      []*Invoice             `protobuf:"bytes,1,rep,name=invoices,proto3" json:"invoices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllInvoicesResponse) Reset() {
	*x = GetAllInvoicesResponse{}
	mi := &file_grpc_proto_invoice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllInvoicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllInvoicesResponse) ProtoMessage() {}

func (x *GetAllInvoicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_invoice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllInvoicesResponse.ProtoReflect.Descriptor instead.
func (*GetAllInvoicesResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_invoice_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllInvoicesResponse) GetInvoices() []*Invoice {
	if x != nil {
		return x.Invoices
	}
	return nil
}

type GetInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoice       *Invoice               `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoiceResponse) Reset() {
	*x = GetInvoiceResponse{}
	mi := &file_grpc_proto_invoice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceResponse) ProtoMessage() {}

func (x *GetInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_invoice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceResponse.ProtoReflect.Descriptor instead.
func (*GetInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_invoice_proto_rawDescGZIP(), []int{7}
}

func (x *GetInvoiceResponse) GetInvoice() *Invoice {
	if x != nil {
		return x.Invoice
	}
	return nil
}

type CreateInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoice       *Invoice               `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvoiceResponse) Reset() {
	*x = CreateInvoiceResponse{}
	mi := &file_grpc_proto_invoice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceResponse) ProtoMessage() {}

func (x *CreateInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_invoice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoiceResponse.ProtoReflect.Descriptor instead.
func (*CreateInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_invoice_proto_rawDescGZIP(), []int{8}
}

func (x *CreateInvoiceResponse) GetInvoice() *Invoice {
	if x != nil {
		return x.Invoice
	}
	return nil
}

type UpdateInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoice       *Invoice               `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInvoiceResponse) Reset() {
	*x = UpdateInvoiceResponse{}
	mi := &file_grpc_proto_invoice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInvoiceResponse) ProtoMessage() {}

func (x *UpdateInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_invoice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInvoiceResponse.ProtoReflect.Descriptor instead.
func (*UpdateInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_invoice_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateInvoiceResponse) GetInvoice() *Invoice {
	if x != nil {
		return x.Invoice
	}
	return nil
}

type DeleteInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoice       *Invoice               `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInvoiceResponse) Reset() {
	*x = DeleteInvoiceResponse{}
	mi := &file_grpc_proto_invoice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInvoiceResponse) ProtoMessage() {}

func (x *DeleteInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_invoice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInvoiceResponse.ProtoReflect.Descriptor instead.
func (*DeleteInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_invoice_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteInvoiceResponse) GetInvoice() *Invoice {
	if x != nil {
		return x.Invoice
	}
	return nil
}

var File_grpc_proto_invoice_proto protoreflect.FileDescriptor

const file_grpc_proto_invoice_proto_rawDesc = "" +
	"\n" +
	"\x18grpc-proto/invoice.proto\x12\tmcpserver\"u\n" +
	"\aInvoice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x02R\x06amount\"\x17\n" +
	"\x15GetAllInvoicesRequest\"#\n" +
	"\x11GetInvoiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"r\n" +
	"\x14CreateInvoiceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x02R\x06amount\"\xc0\x01\n" +
	"\x14UpdateInvoiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\tH\x01R\x06status\x88\x01\x01\x12\x1b\n" +
	"\x06method\x18\x04 \x01(\tH\x02R\x06method\x88\x01\x01\x12\x1b\n" +
	"\x06amount\x18\x05 \x01(\x02H\x03R\x06amount\x88\x01\x01B\a\n" +
	"\x05_nameB\t\n" +
	"\a_statusB\t\n" +
	"\a_methodB\t\n" +
	"\a_amount\"&\n" +
	"\x14DeleteInvoiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x16GetAllInvoicesResponse\x12.\n" +
	"\binvoices\x18\x01 \x03(\v2\x12.mcpserver.InvoiceR\binvoices\"B\n" +
	"\x12GetInvoiceResponse\x12,\n" +
	"\ainvoice\x18\x01 \x01(\v2\x12.mcpserver.InvoiceR\ainvoice\"E\n" +
	"\x15CreateInvoiceResponse\x12,\n" +
	"\ainvoice\x18\x01 \x01(\v2\x12.mcpserver.InvoiceR\ainvoice\"E\n" +
	"\x15UpdateInvoiceResponse\x12,\n" +
	"\ainvoice\x18\x01 \x01(\v2\x12.mcpserver.InvoiceR\ainvoice\"E\n" +
	"\x15DeleteInvoiceResponse\x12,\n" +
	"\ainvoice\x18\x01 \x01(\v2\x12.mcpserver.InvoiceR\ainvoice2\xb2\x03\n" +
	"\x0eInvoiceService\x12U\n" +
	"\x0eGetAllInvoices\x12 .mcpserver.GetAllInvoicesRequest\x1a!.mcpserver.GetAllInvoicesResponse\x12M\n" +
	"\x0eGetInvoiceByID\x12\x1c.mcpserver.GetInvoiceRequest\x1a\x1d.mcpserver.GetInvoiceResponse\x12R\n" +
	"\rCreateInvoice\x12\x1f.mcpserver.CreateInvoiceRequest\x1a .mcpserver.CreateInvoiceResponse\x12R\n" +
	"\rUpdateInvoice\x12\x1f.mcpserver.UpdateInvoiceRequest\x1a .mcpserver.UpdateInvoiceResponse\x12R\n" +
	"\rDeleteInvoice\x12\x1f.mcpserver.DeleteInvoiceRequest\x1a .mcpserver.DeleteInvoiceResponseB\x1cZ\x1agrpc-proto/invoice;invoiceb\x06proto3"

var (
	file_grpc_proto_invoice_proto_rawDescOnce sync.Once
	file_grpc_proto_invoice_proto_rawDescData []byte
)

func file_grpc_proto_invoice_proto_rawDescGZIP() []byte {
	file_grpc_proto_invoice_proto_rawDescOnce.Do(func() {
		file_grpc_proto_invoice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_proto_invoice_proto_rawDesc), len(file_grpc_proto_invoice_proto_rawDesc)))
	})
	return file_grpc_proto_invoice_proto_rawDescData
}

var file_grpc_proto_invoice_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_grpc_proto_invoice_proto_goTypes = []any{
	(*Invoice)(nil),                // 0: mcpserver.Invoice
	(*GetAllInvoicesRequest)(nil),  // 1: mcpserver.GetAllInvoicesRequest
	(*GetInvoiceRequest)(nil),      // 2: mcpserver.GetInvoiceRequest
	(*CreateInvoiceRequest)(nil),   // 3: mcpserver.CreateInvoiceRequest
	(*UpdateInvoiceRequest)(nil),   // 4: mcpserver.UpdateInvoiceRequest
	(*DeleteInvoiceRequest)(nil),   // 5: mcpserver.DeleteInvoiceRequest
	(*GetAllInvoicesResponse)(nil), // 6: mcpserver.GetAllInvoicesResponse
	(*GetInvoiceResponse)(nil),     // 7: mcpserver.GetInvoiceResponse
	(*CreateInvoiceResponse)(nil),  // 8: mcpserver.CreateInvoiceResponse
	(*UpdateInvoiceResponse)(nil),  // 9: mcpserver.UpdateInvoiceResponse
	(*DeleteInvoiceResponse)(nil),  // 10: mcpserver.DeleteInvoiceResponse
}
var file_grpc_proto_invoice_proto_depIdxs = []int32{
	0,  // 0: mcpserver.GetAllInvoicesResponse.invoices:type_name -> mcpserver.Invoice
	0,  // 1: mcpserver.GetInvoiceResponse.invoice:type_name -> mcpserver.Invoice
	0,  // 2: mcpserver.CreateInvoiceResponse.invoice:type_name -> mcpserver.Invoice
	0,  // 3: mcpserver.UpdateInvoiceResponse.invoice:type_name -> mcpserver.Invoice
	0,  // 4: mcpserver.DeleteInvoiceResponse.invoice:type_name -> mcpserver.Invoice
	1,  // 5: mcpserver.InvoiceService.GetAllInvoices:input_type -> mcpserver.GetAllInvoicesRequest
	2,  // 6: mcpserver.InvoiceService.GetInvoiceByID:input_type -> mcpserver.GetInvoiceRequest
	3,  // 7: mcpserver.InvoiceService.CreateInvoice:input_type -> mcpserver.CreateInvoiceRequest
	4,  // 8: mcpserver.InvoiceService.UpdateInvoice:input_type -> mcpserver.UpdateInvoiceRequest
	5,  // 9: mcpserver.InvoiceService.DeleteInvoice:input_type -> mcpserver.DeleteInvoiceRequest
	6,  // 10: mcpserver.InvoiceService.GetAllInvoices:output_type -> mcpserver.GetAllInvoicesResponse
	7,  // 11: mcpserver.InvoiceService.GetInvoiceByID:output_type -> mcpserver.GetInvoiceResponse
	8,  // 12: mcpserver.InvoiceService.CreateInvoice:output_type -> mcpserver.CreateInvoiceResponse
	9,  // 13: mcpserver.InvoiceService.UpdateInvoice:output_type -> mcpserver.UpdateInvoiceResponse
	10, // 14: mcpserver.InvoiceService.DeleteInvoice:output_type -> mcpserver.DeleteInvoiceResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_grpc_proto_invoice_proto_init() }
func file_grpc_proto_invoice_proto_init() {
	if File_grpc_proto_invoice_proto != nil {
		return
	}
	file_grpc_proto_invoice_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_proto_invoice_proto_rawDesc), len(file_grpc_proto_invoice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_invoice_proto_goTypes,
		DependencyIndexes: file_grpc_proto_invoice_proto_depIdxs,
		MessageInfos:      file_grpc_proto_invoice_proto_msgTypes,
	}.Build()
	File_grpc_proto_invoice_proto = out.File
	file_grpc_proto_invoice_proto_goTypes = nil
	file_grpc_proto_invoice_proto_depIdxs = nil
}
