# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_proto import invoice_pb2 as grpc__proto_dot_invoice__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_proto/invoice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InvoiceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllInvoices = channel.unary_unary(
                '/mcpserver.InvoiceService/GetAllInvoices',
                request_serializer=grpc__proto_dot_invoice__pb2.GetAllInvoicesRequest.SerializeToString,
                response_deserializer=grpc__proto_dot_invoice__pb2.GetAllInvoicesResponse.FromString,
                _registered_method=True)
        self.GetInvoiceByID = channel.unary_unary(
                '/mcpserver.InvoiceService/GetInvoiceByID',
                request_serializer=grpc__proto_dot_invoice__pb2.GetInvoiceRequest.SerializeToString,
                response_deserializer=grpc__proto_dot_invoice__pb2.GetInvoiceResponse.FromString,
                _registered_method=True)
        self.CreateInvoice = channel.unary_unary(
                '/mcpserver.InvoiceService/CreateInvoice',
                request_serializer=grpc__proto_dot_invoice__pb2.CreateInvoiceRequest.SerializeToString,
                response_deserializer=grpc__proto_dot_invoice__pb2.CreateInvoiceResponse.FromString,
                _registered_method=True)
        self.UpdateInvoice = channel.unary_unary(
                '/mcpserver.InvoiceService/UpdateInvoice',
                request_serializer=grpc__proto_dot_invoice__pb2.UpdateInvoiceRequest.SerializeToString,
                response_deserializer=grpc__proto_dot_invoice__pb2.UpdateInvoiceResponse.FromString,
                _registered_method=True)
        self.DeleteInvoice = channel.unary_unary(
                '/mcpserver.InvoiceService/DeleteInvoice',
                request_serializer=grpc__proto_dot_invoice__pb2.DeleteInvoiceRequest.SerializeToString,
                response_deserializer=grpc__proto_dot_invoice__pb2.DeleteInvoiceResponse.FromString,
                _registered_method=True)


class InvoiceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllInvoices(self, request, context):
        """GET
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInvoiceByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateInvoice(self, request, context):
        """POST
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateInvoice(self, request, context):
        """PUT
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteInvoice(self, request, context):
        """DELETE
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InvoiceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllInvoices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllInvoices,
                    request_deserializer=grpc__proto_dot_invoice__pb2.GetAllInvoicesRequest.FromString,
                    response_serializer=grpc__proto_dot_invoice__pb2.GetAllInvoicesResponse.SerializeToString,
            ),
            'GetInvoiceByID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInvoiceByID,
                    request_deserializer=grpc__proto_dot_invoice__pb2.GetInvoiceRequest.FromString,
                    response_serializer=grpc__proto_dot_invoice__pb2.GetInvoiceResponse.SerializeToString,
            ),
            'CreateInvoice': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateInvoice,
                    request_deserializer=grpc__proto_dot_invoice__pb2.CreateInvoiceRequest.FromString,
                    response_serializer=grpc__proto_dot_invoice__pb2.CreateInvoiceResponse.SerializeToString,
            ),
            'UpdateInvoice': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateInvoice,
                    request_deserializer=grpc__proto_dot_invoice__pb2.UpdateInvoiceRequest.FromString,
                    response_serializer=grpc__proto_dot_invoice__pb2.UpdateInvoiceResponse.SerializeToString,
            ),
            'DeleteInvoice': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteInvoice,
                    request_deserializer=grpc__proto_dot_invoice__pb2.DeleteInvoiceRequest.FromString,
                    response_serializer=grpc__proto_dot_invoice__pb2.DeleteInvoiceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mcpserver.InvoiceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mcpserver.InvoiceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InvoiceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllInvoices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcpserver.InvoiceService/GetAllInvoices',
            grpc__proto_dot_invoice__pb2.GetAllInvoicesRequest.SerializeToString,
            grpc__proto_dot_invoice__pb2.GetAllInvoicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInvoiceByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcpserver.InvoiceService/GetInvoiceByID',
            grpc__proto_dot_invoice__pb2.GetInvoiceRequest.SerializeToString,
            grpc__proto_dot_invoice__pb2.GetInvoiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateInvoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcpserver.InvoiceService/CreateInvoice',
            grpc__proto_dot_invoice__pb2.CreateInvoiceRequest.SerializeToString,
            grpc__proto_dot_invoice__pb2.CreateInvoiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateInvoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcpserver.InvoiceService/UpdateInvoice',
            grpc__proto_dot_invoice__pb2.UpdateInvoiceRequest.SerializeToString,
            grpc__proto_dot_invoice__pb2.UpdateInvoiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteInvoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcpserver.InvoiceService/DeleteInvoice',
            grpc__proto_dot_invoice__pb2.DeleteInvoiceRequest.SerializeToString,
            grpc__proto_dot_invoice__pb2.DeleteInvoiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
