# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc-proto/invoice.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpc-proto/invoice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18grpc-proto/invoice.proto\x12\tmcpserver\"S\n\x07Invoice\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x0e\n\x06method\x18\x04 \x01(\t\x12\x0e\n\x06\x61mount\x18\x05 \x01(\x02\"\x17\n\x15GetAllInvoicesRequest\"\x1f\n\x11GetInvoiceRequest\x12\n\n\x02id\x18\x01 \x01(\t\"T\n\x14\x43reateInvoiceRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0e\n\x06method\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x02\"\x9e\x01\n\x14UpdateInvoiceRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06status\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x06method\x18\x04 \x01(\tH\x02\x88\x01\x01\x12\x13\n\x06\x61mount\x18\x05 \x01(\x02H\x03\x88\x01\x01\x42\x07\n\x05_nameB\t\n\x07_statusB\t\n\x07_methodB\t\n\x07_amount\"\"\n\x14\x44\x65leteInvoiceRequest\x12\n\n\x02id\x18\x01 \x01(\t\">\n\x16GetAllInvoicesResponse\x12$\n\x08invoices\x18\x01 \x03(\x0b\x32\x12.mcpserver.Invoice\"9\n\x12GetInvoiceResponse\x12#\n\x07invoice\x18\x01 \x01(\x0b\x32\x12.mcpserver.Invoice\"<\n\x15\x43reateInvoiceResponse\x12#\n\x07invoice\x18\x01 \x01(\x0b\x32\x12.mcpserver.Invoice\"<\n\x15UpdateInvoiceResponse\x12#\n\x07invoice\x18\x01 \x01(\x0b\x32\x12.mcpserver.Invoice\"<\n\x15\x44\x65leteInvoiceResponse\x12#\n\x07invoice\x18\x01 \x01(\x0b\x32\x12.mcpserver.Invoice2\xb2\x03\n\x0eInvoiceService\x12U\n\x0eGetAllInvoices\x12 .mcpserver.GetAllInvoicesRequest\x1a!.mcpserver.GetAllInvoicesResponse\x12M\n\x0eGetInvoiceByID\x12\x1c.mcpserver.GetInvoiceRequest\x1a\x1d.mcpserver.GetInvoiceResponse\x12R\n\rCreateInvoice\x12\x1f.mcpserver.CreateInvoiceRequest\x1a .mcpserver.CreateInvoiceResponse\x12R\n\rUpdateInvoice\x12\x1f.mcpserver.UpdateInvoiceRequest\x1a .mcpserver.UpdateInvoiceResponse\x12R\n\rDeleteInvoice\x12\x1f.mcpserver.DeleteInvoiceRequest\x1a .mcpserver.DeleteInvoiceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_proto.invoice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INVOICE']._serialized_start=39
  _globals['_INVOICE']._serialized_end=122
  _globals['_GETALLINVOICESREQUEST']._serialized_start=124
  _globals['_GETALLINVOICESREQUEST']._serialized_end=147
  _globals['_GETINVOICEREQUEST']._serialized_start=149
  _globals['_GETINVOICEREQUEST']._serialized_end=180
  _globals['_CREATEINVOICEREQUEST']._serialized_start=182
  _globals['_CREATEINVOICEREQUEST']._serialized_end=266
  _globals['_UPDATEINVOICEREQUEST']._serialized_start=269
  _globals['_UPDATEINVOICEREQUEST']._serialized_end=427
  _globals['_DELETEINVOICEREQUEST']._serialized_start=429
  _globals['_DELETEINVOICEREQUEST']._serialized_end=463
  _globals['_GETALLINVOICESRESPONSE']._serialized_start=465
  _globals['_GETALLINVOICESRESPONSE']._serialized_end=527
  _globals['_GETINVOICERESPONSE']._serialized_start=529
  _globals['_GETINVOICERESPONSE']._serialized_end=586
  _globals['_CREATEINVOICERESPONSE']._serialized_start=588
  _globals['_CREATEINVOICERESPONSE']._serialized_end=648
  _globals['_UPDATEINVOICERESPONSE']._serialized_start=650
  _globals['_UPDATEINVOICERESPONSE']._serialized_end=710
  _globals['_DELETEINVOICERESPONSE']._serialized_start=712
  _globals['_DELETEINVOICERESPONSE']._serialized_end=772
  _globals['_INVOICESERVICE']._serialized_start=775
  _globals['_INVOICESERVICE']._serialized_end=1209
# @@protoc_insertion_point(module_scope)
